# Generated by Django 3.2.12 on 2022-05-13 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=500)),
                ('useless', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_dir', models.CharField(blank=True, max_length=500, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('s_eye', models.IntegerField(blank=True, default=None, null=True)),
                ('s_nose', models.IntegerField(blank=True, default=None, null=True)),
                ('s_cheek', models.IntegerField(blank=True, default=None, null=True)),
                ('s_ear', models.IntegerField(blank=True, default=None, null=True)),
                ('s_whiskas', models.IntegerField(blank=True, default=None, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring.imagefile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='scoring.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imagefile',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='scoring.project'),
        ),
    ]
