# Generated by Django 3.2.12 on 2022-05-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='kappa',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
