# Generated by Django 5.0.6 on 2024-06-08 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='varianz',
            new_name='variance',
        ),
    ]
