# Generated by Django 3.2.12 on 2022-05-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_backup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagescore',
            old_name='s_whiskas',
            new_name='s_whiskers',
        ),
    ]
