# Generated by Django 5.0.6 on 2024-06-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_alter_imagescore_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagefile',
            old_name='variance',
            new_name='stddev',
        ),
    ]
