# Generated by Django 5.0.6 on 2024-06-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_rename_variance_imagefile_stddev'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
