# Generated by Django 3.2.12 on 2022-06-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0004_rename_s_whiskas_imagescore_s_whiskers'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagescore',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
