# Generated by Django 3.2.12 on 2022-05-20 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_imagescore_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='kappa',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='diversity',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
