# Generated by Django 5.0.6 on 2024-08-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0005_backup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='raw_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
